"use client";
import { Geist_Mono, Dosis } from "next/font/google";
import "./globals.css";
import WrapperLoader from "@/components/WrapperLoader";
import { SessionProvider } from 'next-auth/react';
const dosis = Dosis({
  variable: "--font-dosis",
  subsets: ["latin"],
  weight: "400",
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata = {
  title: "DealLance",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preload" href="/logo2.png" as="image" type="image/png" />
      </head>
      <body className={`${dosis.variable} ${geistMono.variable} antialiased`}>
        <SessionProvider>
          <WrapperLoader>
            {children}
          </WrapperLoader>
        </SessionProvider>
      </body>
    </html>
  );
}
